String login = 'login';
String home = 'home';
String categories = 'categories';
String favorites ='favorites';
String profile = 'profile';
String updatePprofile = 'update-profile';
String register = 'register';
String search = 'products/search';
String carts = 'carts';